matrix:
  include:
    - os: osx
      language: cpp

      # You can't use `set -e` in Travis, because the osx environment is very broken.
      install:
        - cd ext/xlnt-1.2.0
        - cmake . || exit 1
        - make || exit 1
        - sudo make install || exit 1
        - cd ../..
        # see travis-ci #9285
        - brew upgrade python3
        - brew install scons
        - brew install qt5
        - brew install pkg-config

      script:
        - export PKG_CONFIG_PATH=/usr/local/opt/qt/lib/pkgconfig
        - scons qt5_dir=/usr/local/opt/qt || exit 1
        - ./build/unit_tests
      #  - ./integration_tests

    - os: linux
      language: cpp
      dist: trusty

      # Xenial will release soon on Travis:
      # https://blog.travis-ci.com/2017-12-01-new-update-schedule-for-linux-build-images

      install:
        - set -e
        - cd ext/xlnt-1.2.0
        - cmake .
        - make
        - sudo make install
        - sudo ldconfig
        - cd ../..

      script:
        - set -e
        - scons
        - ./build/unit_tests
      #  - ./integration_tests

      before_install:
        - sudo apt-get update -qq
        - sudo apt-get install -qq qtbase5-dev qt5-default
