matrix:
  include:
    - os: osx
      language: cpp

      # You can't use `set -e` in Travis, because the osx environment is very broken.
      install:
        - cd ext/xlnt-1.3.0
        - cmake . || exit 1
        - make || exit 1
        - sudo make install || exit 1
        - cd ../..
        # see travis-ci #9285
        - brew upgrade python3
        - brew install scons
        - brew install qt5
        - brew install pkg-config

      script:
        - export PKG_CONFIG_PATH=/usr/local/opt/qt/lib/pkgconfig
        - scons qt5_dir=/usr/local/opt/qt || exit 1
        - ./build/unit_tests
      #  - ./integration_tests
      deploy:
        provider: releases
        api_key:
          secure: az1YJGTmjduWE63/eSmqVCyjndHc9sBGkBmidTyZS5wL5qJtKntivnxwW2mKX6eQomTEZ8aMLqSuQu0LKAFS8++t1CqeJWV9rkzBXmXT3kVRwWUnlqbDOQg+docjoXSy9rtuhQHIMgGW37MyzNpnrxR9oKs8r/lnJNJkiyUzVMvrQERBBg3/VLZgg7MZJJ5pVai1i/O1nZvwql0z3v+4ONI5mnRAoYohubzaG/BwuNGiaevvA1sc4UPitlkBzkkL73GfKarCc+HAl0mklqfxGklningtvRMup5nv/wM+RYFgVbswkK/WpsjyjMrcZLauPZuWnBZNYakk5aM4xKnNdbLaXK3wqbVvr9f06pi0ELjK2xf+PJTCwZZWdYE01L6e+6AA4v+lYPYjFjrhEJJAwSzLVT0883x9wogx6c3MJGr2lKHM63wjeHiPGFJXkIjVXSuJGrFLn/rROV/HAPPF33GtPCdW3ZZUFJp0Ju3JboyTotaD2MCm/biv6qzhpE/wmmXWAaXPIIO1ThMHXNjIzNc92RgYC7txB5DhNpVsrzddi3EV2x8PCGtPv1bYa5apKnSSTYe79zN8BrfLkw/P/dFCj3zgUyXDchJPZnN7u1WO0wR9bs9TX80UHKqBT/OeTMTteQUMWjYfbhylWGPq0t1dhj8NoQcG5buqHLiSW+4=
        file_glob: true
        file: build/figshare_uploader-*.dmg
        skip_cleanup: true
        on:
          tags: true

    - os: linux
      language: cpp
      dist: trusty

      # Xenial will release soon on Travis:
      # https://blog.travis-ci.com/2017-12-01-new-update-schedule-for-linux-build-images

      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
    
      install:
        - set -e
        - export CC=gcc-6
        - export CXX=g++-6
        - cd ext/xlnt-1.3.0
        - cmake .
        - make
        - sudo make install
        - sudo ldconfig
        - cd ../..

      script:
        - set -e
        - export CXX=g++-6
        - scons
        - ./build/unit_tests
      #  - ./integration_tests

      before_install:
        - sudo apt-get update -qq
        - sudo apt-get install -qq qtbase5-dev qt5-default
