#ifndef ARTICLE_TYPES_HH
#define ARTICLE_TYPES_HH

enum class ArticleType {
    FIGURE, MEDIA, DATASET, FILESET, POSTER, PAPER, PRESENTATION, THESIS,
    CODE, METADATA
};

#endif // ARTICLE_TYPES_HH
